defaults: &default
  adapter: solr
  url: <%= ENV['SOLR_URL']  %>
  replicate_master_url: <%= ENV['SOLR_REPLICATE_MASTER_URL'] %>

development:
  <<: *default
demo:
  <<: *default
test:
  <<: *default
production:
  <<: *default
